import pandas as pd


def extract_book_genre_info(entry: pd.Series) -> pd.Series:
    """Use Goodreads shelf count information (number of times
    people assign a shelf to a book) to generate most appropriate
    genre(s) for books. Many shelves don't correspond to book genres;
    these are removed during the "genre_filter" step. Genres are simplified
    using the genre_dict, which maps subgenres to broader genres.

    Args:
        entry (pd.Series): Goodreads shelves and corresponding counts
            for a series of books.

    Returns:
        Up to three genres for each book.
    """
    genre_info = pd.DataFrame(eval(entry))
    genre_info = genre_info.rename(columns={"@count": "counts", "@name": "genre"})
    search_pattern = "|".join(genre_filter)
    m_bad_genres = genre_info.genre.str.contains(search_pattern)
    clean_genre = genre_info[~m_bad_genres].copy()

    clean_genre = clean_genre.reset_index(drop=True)
    clean_genre["filt_genre"] = clean_genre.genre.map(genre_dict)
    clean_genre["counts"] = clean_genre.counts.astype(int)

    total = clean_genre.groupby("filt_genre").sum().sum()
    counts_df = (clean_genre.groupby("filt_genre").sum() / total).sort_values(
        by="counts"
    )
    book_genre = [i for i in counts_df[counts_df.counts > 0.25].index]
    return book_genre


# generating a filter for goodreads shelves
# (i.e. categories that don't correspond to book genres)
genre_filter = [
    "to-read",
    "favorites",
    "currently-reading",
    "books-i-own",
    "owned",
    "series",
    "favourites",
    "owned-books",
    "book-club",
    "kindle",
    "my-books",
    "favorite-books",
    "read-in-2012",
    "re-read",
    "all-time-favorites",
    "5-stars",
    "books",
    "bookclub",
    "audible",
    "audio-books",
    "favorite",
    "audiobook",
    "novels",
    "ebook",
    "i-own",
    "audiobooks",
    "meh",
    "dnf",
    "have",
    "audio-book",
    "read-in-2011",
    "my-favorites",
    "default",
    "library",
    "books-i-have",
    "did-not-finish",
    "recommended",
    "translated",
    "must-read",
    "book-club-books",
    "millennium",
    "five-stars",
    "didn-t-finish",
    "never-finished",
    "ebooks",
    "read-2012",
    "reread",
    "faves",
    "my-library",
    "read-in-2010",
    "audio",
    "unfinished",
    "shelfari-favorites",
    "favs",
    "finished",
    "own-it",
    "favorite-series",
    "english",
    "abandoned",
    "paperback",
    "loved",
    "novel",
    "read-more-than-once",
    "read-in-2013",
    "borrowed",
    "on-my-shelf",
    "read-2010",
    "favourite",
    "want-to-buy",
    "to-buy",
    "bookshelf",
    "my-bookshelf",
    "4-stars",
    "already-read",
    "page-turner",
    "best-books",
    "favourite-books",
    "trilogy",
    "read-2011",
    "re-reads",
    "5-star",
    "reviewed",
    "e-book",
    "never-again",
    "read-in-2009",
    "read-in-2008",
    "4-star",
    "3-star",
    "2-star",
    "1-star",
    "0-star",
    "3-stars",
    "2-star",
    "1-star",
    "0-star",
    "read-in-",
    "-star",
    "-stars",
    "movie",
    "chick-lit",
    "guilty-pleasure",
    "recommend",
    "wish-list",
    "book-group" "on-hold",
    "read-",
    "stand-alone",
    "made-me-cry",
    "gave-up-on",
    "gave-up",
    "i-only-watched-the-movie",
    "owned-to-read",
    "couldn-t-finish",
    "could-not-finish",
    "best-ever",
]


# generating a white list for book genres
genre_dict = {
    "young-adult-fiction": "fiction",
    "ya-paranormal": "fantasy",
    "ya-fantasy": "fantasy",
    "ya-dystopian": "science-fiction",
    "teen-fiction": "fiction",
    "young-adult-fantasy": "fantasy",
    "ya-fiction": "fiction",
    "ya-historical-fiction": "fiction",
    "horror": "fiction",
    "horror-suspense": "fiction",
    "terror": "fiction",
    "fiction-horror": "fiction",
    "gothic": "fiction",
    "adult-fiction": "fiction",
    "southern-fiction": "fiction",
    "literary-fiction": "fiction",
    "juvenile-fiction": "fiction",
    "fiction": "fiction",
    "realistic-fiction": "fiction",
    "modern-fiction": "fiction",
    "general-fiction": "fiction",
    "popular-fiction": "fiction",
    "metafiction": "fiction",
    "animal-fiction": "fiction",
    "fiction-historical": "fiction",
    "classic-fiction": "fiction",
    "contemporary-fiction": "fiction",
    "historical-fiction": "fiction",
    "historical-fic": "fiction",
    "historic-fiction": "fiction",
    "dystopian": "science-fiction",
    "dystopia": "science-fiction",
    "post-apocalyptic": "science-fiction",
    "distopia": "science-fiction",
    "distopian": "science-fiction",
    "dystopian-fiction": "science-fiction",
    "speculative-fiction": "science-fiction",
    "dystopias": "science-fiction",
    "science-fiction-fantasy": "science-fiction",
    "adventure": "fiction",
    "science-fiction": "science-fiction",
    "sci-fi": "science-fiction",
    "futuristic": "science-fiction",
    "future": "science-fiction",
    "sci-fi-fantasy": "science-fiction",
    "scifi": "science-fiction",
    "scifi-fantasy": "science-fiction",
    "sf": "science-fiction",
    "space opera": "science-fiction",
    "space-opera": "science-fiction",
    "sff": "science-fiction",
    "aliens": "science-fiction",
    "sf-fantasy": "science-fiction",
    "sci-fi-and-fantasy": "science-fiction",
    "sciencefiction": "science-fiction",
    "far-future": "science-fiction",
    "first-contact": "science-fiction",
    "utopia": "science-fiction",
    "science-fiction-and-fantasy": "science-fiction",
    "hard-sci-fi": "science-fiction",
    "sf-f": "science-fiction",
    "fantasy": "fantasy",
    "high-fantasy": "fantasy",
    "fantasy-sci-fi": "fantasy",
    "paranormal-fantasy": "fantasy",
    "paranormal": "fantasy",
    "vampires": "fantasy",
    "vampire": "fantasy",
    "vamps": "fantasy",
    "urban-fantasy": "fantasy",
    "supernatural": "fantasy",
    "werewolves": "fantasy",
    "fairy-tales": "fantasy",
    "fairy tales": "fantasy",
    "fairy-tale": "fantasy",
    "fantasy-paranormal": "fantasy",
    "epic fantasy": "fantasy",
    "epic-fantasy": "fantasy",
    "fantasia": "fantasy",
    "fantasy-fiction": "fantasy",
    "mythology": "fantasy",
    "magic": "fantasy",
    "witches": "fantasy",
    "wizards": "fantasy",
    "dragons": "fantasy",
    "shapeshifters": "fantasy",
    "shifters": "fantasy",
    "werewolf": "fantasy",
    "ghosts": "fantasy",
    "ghost-stories": "fantasy",
    "fiction-fantasy": "fantasy",
    "fantasy-scifi": "fantasy",
    "magical-realism": "fantasy",
    "fantasy-science-fiction": "fantasy",
    "genre-fantasy": "fantasy",
    "fantasy-and-sci-fi": "fantasy",
    "dark-fantasy": "fantasy",
    "horror-supernatural": "fantasy",
    "fantastic": "fantasy",
    "romance": "romance",
    "pnr": "romance",
    "love": "romance",
    "love-triangle": "romance",
    "paranormal-romance": "romance",
    "romantic": "romance",
    "historical-romance": "romance",
    "gothic-romance": "romance",
    "thriller": "thriller",
    "thrillers": "thriller",
    "psychological-thriller": "thriller",
    "thriller-mystery": "thriller",
    "thriller-suspense": "thriller",
    "suspense": "thriller",
    "suspense-thriller": "thriller",
    "conspiracy": "thriller",
    "medical-thriller": "thriller",
    "mystery": "mystery",
    "mystery-thriller": "mystery",
    "mystery-suspense": "mystery",
    "mystery-crime": "mystery",
    "mysteries": "mystery",
    "historical-mystery": "mystery",
    "historical mystery": "mystery",
    "forensic-mystery": "mystery",
    "classic-mystery": "mystery",
    "classic mystery": "mystery",
    "fiction-mystery": "mystery",
    "murder-mystery": "mystery",
    "cozy-mystery": "mystery",
    "golden-age-mystery": "mystery",
    "mysteries-thrillers": "mystery",
    "mystery-thrillers": "mystery",
    "classic-mysteries": "mystery",
    "mystery-classic": "mystery",
    "mystery-detective": "mystery",
    "mystery-cozy": "mystery",
    "golden-age-mysteries": "mystery",
    "mystery-thriller-suspense": "mystery",
    "forensic-mysteries": "mystery",
    "crime-mystery-thriller": "thriller",
    "crime": "thriller",
    "crime-fiction": "thriller",
    "crime-thriller": "thriller",
    "crime-mystery": "thriller",
    "horror-thriller": "thriller",
    "murder": "thriller",
    "detective": "thriller",
    "detectives": "thriller",
    "detective-fiction": "thriller",
    "thriller-horror": "thriller",
    "crime-thrillers": "thriller",
    "crime-and-mystery": "thriller",
    "serial killer": "thriller",
    "serial-killers": "thriller",
    "serial-killer": "thriller",
    "informational": "non-fiction",
    "science": "non-fiction",
    "math-and-science": "non-fiction",
    "plants": "non-fiction",
    "nature": "non-fiction",
    "war": "non-fiction",
    "holocaust": "non-fiction",
    "wwii": "non-fiction",
    "ww2": "non-fiction",
    "world-war-2": "non-fiction",
    "world-war-ii": "non-fiction",
    "world-war-ll": "non-fiction",
    "german-occupation": "non-fiction",
    "historical": "non-fiction",
    "1800s": "non-fiction",
    "1900s": "non-fiction",
    "1910s": "non-fiction",
    "1920s": "non-fiction",
    "1930s": "non-fiction",
    "1940s": "non-fiction",
    "1950s": "non-fiction",
    "1960s": "non-fiction",
    "1970s": "non-fiction",
    "1980s": "non-fiction",
    "1990s": "non-fiction",
    "18th-century": "non-fiction",
    "19th-century": "non-fiction",
    "history": "non-fiction",
    "contemporary": "non-fiction",
    "modern": "non-fiction",
    "civil-rights": "non-fiction",
    "segregation": "non-fiction",
    "racial-discrimination": "non-fiction",
    "racism": "non-fiction",
    "death": "thriller",
    "dark": "thriller",
    "classic-literature": "non-fiction",
    "classic-lit": "non-fiction",
    "literature": "non-fiction",
    "literary": "non-fiction",
    "non-fiction": "non-fiction",
    "nonfiction": "non-fiction",
    "religion": "non-fiction",
    "psychology": "non-fiction",
    "medical": "non-fiction",
    "mental-health": "non-fiction",
    "autism": "non-fiction",
    "mental-illness": "non-fiction",
    "disability": "non-fiction",
    "philosophy": "non-fiction",
    "general-non-fiction": "non-fiction",
    "faith": "non-fiction",
    "journalism": "non-fiction",
    "biography": "non-fiction",
    "true-crime": "non-fiction",
    "non-fic": "non-fiction",
    "nonfic": "non-fiction",
    "adult-nonfiction": "non-fiction",
    "sociology": "non-fiction",
    "religious": "non-fiction",
    "spirituality": "non-fiction",
    "religion-spirituality": "non-fiction",
    "religion-and-spirituality": "non-fiction",
    "faith-spirituality": "non-fiction",
    "spiritual": "non-fiction",
    "spirituality-religion": "non-fiction",
    "atheism": "non-fiction",
    "memoir": "non-fiction",
    "adult-non-fiction": "non-fiction",
    "narrative-nonfiction": "non-fiction",
    "true": "non-fiction",
    "theology": "non-fiction",
    "seasons": "non-fiction",
    "flowers": "non-fiction",
    "immigration": "non-fiction",
    "social studies": "non-fiction",
    "travel": "non-fiction",
    "disease": "non-fiction",
    "fever": "non-fiction",
    "epidemic": "non-fiction",
    "yellow-fever": "non-fiction",
    "biographies": "non-fiction",
    "mathematics": "non-fiction",
    "biography-memoir": "non-fiction",
    "math": "non-fiction",
    "economics": "non-fiction",
    "memoir-biography": "non-fiction",
    "bio": "non-fiction",
    "biography-autobiography": "non-fiction",
    "memoirs": "non-fiction",
    "schizophrenia": "non-fiction",
    "biographies-memoirs": "non-fiction",
    "biographical": "non-fiction",
    "biography-and-memoir": "non-fiction",
    "maths": "non-fiction",
    "math-concepts": "non-fiction",
    "counting": "non-fiction",
    "autobiography": "non-fiction",
    "history-biography": "non-fiction",
    "bio-memoir": "non-fiction",
    "memoir-autobiography": "non-fiction",
    "essays": "non-fiction",
    "self-help": "non-fiction",
    "creative-nonfiction": "non-fiction",
    "culture": "non-fiction",
    "artificial-intelligence": "non-fiction",
    "slavery": "non-fiction",
    "feminism": "non-fiction",
    "victorian": "non-fiction",
    "spring": "non-fiction",
    "gardening": "non-fiction",
    "garden": "non-fiction",
    "environment": "non-fiction",
    "cancer": "non-fiction",
    "graphic-memoir": "non-fiction",
    "art": "non-fiction",
    "sports": "non-fiction",
    "realistic": "non-fiction",
    "forensic": "non-fiction",
    "forensics": "non-fiction",
    "forensic-science": "non-fiction",
    "anthropology": "non-fiction",
    "education": "non-fiction",
    "learning": "non-fiction",
}
